name: demo-2

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: create a text file
      run: echo "hello, world!" > hello.txt
    - name: read file
      run: cat hello.txt:wq
      
